version: '3'

services:

  flask-app:
    build: .
    ports:
      - "8000:8000"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    depends_on:
      - flask-app

  clamav:
    image: mkodockx/docker-clamav
    container_name: clamav
    restart: always
    ports:
      - "3310:3310"
    volumes:
      - clamav_data:/data
  
volumes:
    mongodb_data:
    clamav_data:
