version: '3'

services:

  flask-app:
    build: .
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask-app


  clamav:
    image: mkodockx/docker-clamav
    container_name: clamav
    restart: always
    ports:
      - "80:80"
    volumes:
      - clamav_data:/data

  volumes:
  clamav_data: