version: '3'

services:

  flask-app:
    build: .
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask-app

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    depends_on:
      - flask-app

  clamav:
    image: mkodockx/docker-clamav
    container_name: clamav
    restart: always
    ports:
      - "3310:3310"
    volumes:
      - clamav_data:/data
    depends_on:
      - nginx 
  
volumes:
    mongodb_data:
    clamav_data: