version: '3'

services:

  prometheus:
    image: prom/prometheus
    restart: always
    networks:
      - log-network

  grafana:
    image: grafana/grafana
    restart: always
    networks:
      - log-network    

networks:
  log-network: