version: "3.3"
services:
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment: 
      - FLASK_SERVER_ADDR=backend:9091  
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 81:80
    restart: always
    depends_on:
      - api_endpoint

  api_endpoint:
    build:
      context: flask_api
      dockerfile: Dockerfile
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=9091
    #volumes:
    #  - ./flask:/var/lib/flask_api
    depends_on:
      -  mongo  

  mongo:
    image: mongo
