version: '3'

services:

  flask-app:
    build: .
    ports:
      - "8000:8000"

  clamav:
    image: mkodockx/docker-clamav
    container_name: clamav
    restart: always
    ports:
      - "3310:3310"
    volumes:
      - clamav_data:/data

volumes:
  clamav_data: